#!/bin/sh

# Check for commitlint errors
npx --no-install commitlint --edit "$1" 

# Check for uncommitted database schema changes
#
DIFF_OUTPUT=$(supabase db diff)

if [ -n "$DIFF_OUTPUT" ]; then
  echo "Uncommitted database schema changes detected. Please commit the changes."
  exit 1
else
  echo "No uncommitted database schema changes detected."
fi


npm run lint

npm run build

npm run test:e2e
